import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <input type='text' placeholder='search' />
        <h1>
          <a href='/'>WEB</a>
        </h1>
        <ol>
          <li>
            <a href='/read/1'>html</a>
          </li>
          <li>
            <a href='/read/2'>css</a>
          </li>
        </ol>
        <div
          style={{
            padding: '30px 10px',
            border: '1px solid',
            borderRadius: '10px',
          }}
        >
          {children}
        </div>
        <h2>WEB</h2>
        HELLO, WEB!
        <ul>
          <li>
            <a href='/create'>create</a>
          </li>
          <li>
            <a href='/update/1'>update</a>
          </li>
          <li>
            <button> delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
