import Link from 'next/link';
import { Controller } from './component/Controller';
import './globals.css';

export const metadata = {
  title: 'Page Title',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const res = await fetch('http://localhost:5000/topics', {
    cache: 'no-store',
  });
  const topics = await res.json();

  return (
    <html lang='en'>
      <body>
        <input type='text' placeholder='search' />
        <h1>
          <a href='/'>WEB</a>
        </h1>
        <ol>
          {topics.map(topic => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        <div
          style={{
            padding: '30px 10px',
            border: '1px solid',
            borderRadius: '10px',
          }}
        >
          {children}
          <Controller />
        </div>
      </body>
    </html>
  );
}
